# Generated by Django 4.2 on 2024-05-22 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Usuario",
            new_name="CustomUser",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="nombre",
            new_name="name",
        ),
    ]
